# Generated by Django 3.1.7 on 2021-05-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210413_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, null=True, verbose_name='url')),
                ('mall', models.URLField(null=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_products', to='post.post')),
            ],
            options={
                'db_table': 'crawl_products',
            },
        ),
        migrations.RemoveField(
            model_name='crawlmall',
            name='post',
        ),
        migrations.DeleteModel(
            name='CrawlImage',
        ),
        migrations.DeleteModel(
            name='CrawlMall',
        ),
    ]
